---
title: "SILAC (patient 905, 180 & 40 spd) QC Report: 2 & 6 h"
author: "Giulia Franciosa"
format: 
  html:
    embed-resources: true
    theme: cosmo
    code-fold: true
    toc: true
params:
  subfolder: "Prot_180spd_patient09_2h" # Default for testing
---

## 1. Setup and load libraries
```{r setup}
#| message: false
#| warning: false

# 1. Load standard analysis libraries
library(tidyverse)
library(data.table)
library(arrow)
library(here)
library(RColorBrewer)

# 2. Load the function
source(here("R", "clean_diann_report.R"))

# 3. Define output directory based on the parameter
output_dir <- here("results", "SILAC_Proteome", params$subfolder)
```

## 2. Load and clean the data
```{r load-data}
#| message: false
#| warning: false

# 1. Define the path to the data
input_path <- here("data", "SILAC_Proteome", params$subfolder, "report.parquet")

# 2. Read the file and clean the data
report <- clean_diann_data(input_path)
cat("Number of rows:", nrow(report), "\n")
```

## 3. Data renaming and add metadata
```{r data-specific-renaming}
#| message: false
#| warning: false

# 1. Clean Run Names
report$Run <- sub("^.*Human_05_", "", report$Run)
cat("Unique Runs after cleaning:\n")
cat(sort(unique(report$Run)), sep = "\n")

# 2. Add metadata columns
report$condition <- substr(report$Run, 1, nchar(report$Run) - 9)
cat("Unique conditions:\n")
cat(unique(report$condition), sep = "\n")
report$condition <- factor(
  report$condition,
  levels = c(
    "Ratio11_Ctrl",
    "TCL_Ctrl",
    "TILs_Ctrl",
    "Co",
    "Co_TCL",
    "Co_TILs"
  )
)

# 3. Save filtered data
arrow::write_parquet(report, file.path(output_dir, "report_filtered.parquet"))
```

## 4. Id Count
```{r count}
#| message: false
#| warning: false

# 1. Calculate protein counts per Channel and Run
pg_count <- report %>%
  group_by(Channel, condition, Run) %>%
  summarise(n = n_distinct(Protein.Group), .groups = "drop")

# 2. Calculate precursor counts per Channel and Run
pr_count <- report %>%
  group_by(Channel, condition, Run) %>%
  summarise(n = n_distinct(Precursor.Id), .groups = "drop")

# 3. Save Count Tables
write_tsv(pg_count, file.path(output_dir, "Count.PG.per-run.txt"))
write_tsv(pr_count, file.path(output_dir, "Count.pr.per-run.txt"))
```

## 5. Plot Count Data
```{r plot-counts}
#| message: false
#| warning: false

# 1. Exclude bad runs
bad_runs <- pg_count %>%
  group_by(Run) %>%
  summarise(max_n = max(n, na.rm = TRUE)) %>%
  filter(max_n < 200) %>%
  pull(Run)

# 2. Print bad runs
if(length(bad_runs) > 0) {
  cat("Removing the following low-quality runs (< 200 IDs):\n")
  print(bad_runs)
} else {
  cat("No runs removed.\n")
}

# 3. Prepare Protein Group stats
Id_stats <- pg_count %>%
  #remove bad runs
  filter(!Run %in% bad_runs) %>%
  #calculate Mean and SD
  group_by(condition, Channel) %>%
  summarise(
    mean = mean(n, na.rm = TRUE),
    st.dev = sd(n, na.rm = TRUE),
    .groups = "drop"
  )

# 4. Define the y axis limits
# Find the highest point on the plot (Mean + Error Bar)
max_val <- max(Id_stats$mean + Id_stats$st.dev, na.rm = TRUE)
# Add 2000 buffer and round to the nearest 1000 for a clean axis
y_limit <- round(max_val + 2000, digits = -3)

# 5. Plot Protein Group Counts
ggplot(Id_stats, aes(x = condition, y = mean, fill = Channel)) +
  geom_bar(
    stat = "identity",
    position = position_dodge(),
    colour = "black",
    lwd = 0.2
  ) +
  geom_errorbar(
    aes(ymin = mean - st.dev, ymax = mean + st.dev),
    width = 0.2,
    position = position_dodge(width = 0.9)
  ) +
  geom_text(
    aes(label = round(mean, 0)),
    position = position_dodge(width = 0.9),
    vjust = -2,
    size = 3
  ) +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal(base_size = 12) +
  labs(
    title = paste("Protein IDs:", params$subfolder),
    y = "PG Count",
    x = ""
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(
    limits = c(0, y_limit),
    breaks = seq(0, y_limit, by = 2000)
  )
```
